name: Automation Web and API Workflow

on:
  workflow_dispatch:
    inputs: { }
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-api-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute API Test
        run: ./gradlew apiTest

      - name: Archive Test Result
        uses: actions/upload-artifact@v3.1.0
        if: always ()
        with:
          name: cucumber
          path: reports

